name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
    
    - name: Install dependencies
      run: |
        uv venv 
        uv pip install .
        uv pip install ".[dev]"
    
    - name: Run tests
      run: uv run pytest
    
    # - name: Lint with ruff
    #   run: uv run ruff check .
    
    # - name: Check formatting with black
    #   run: uv run black --check .
    
    # - name: Check imports with isort
    #   run: uv run isort --check .
    
    # - name: Type check with mypy
    #   run: uv run mypy .